DNN-20025: Make PurgePage class testable
dnnsoftware/Dnn.AdminExperience.Library pull request #146
Opened 2018-05-02 17:52 UTC by Mohtshum

- Introduce a new class ContentVerifier : IContentVerifier, which takes IPortalGroupController and IPortalController as dependencies
- Add static ContentVerifier field in PortalHelper
- Make PortalHelper.IsContentExistsForRequestedPortal forward calls to ContentVerifier
- Mark PortalHelper obsolete

2018-05-03 07:07 UTC, tpluscode requested changes
This is great. Just minor finishing touches and we'll merge ASAP

2018-05-03 07:07 UTC, tpluscode commented on src/Dnn.PersonaBar.Library/Helper/PortalHelper.cs
> +        private bool IsRequestForSiteGroup(int portalId, int portalIdSiteGroup)
This is no longer used and can be removed

2018-05-03 07:07 UTC, tpluscode commented on src/Dnn.PersonaBar.Library/Helper/PortalHelper.cs
> +        static readonly IContentVerifier contentVerifier = new ContentVerifier(PortalController.Instance, PortalGroupController.Instance);
Please add `private` modifier and rename in PascalCase

2018-05-03 07:07 UTC, tpluscode commented on src/Dnn.PersonaBar.Library/Helper/ContentVerifier.cs
> +        public ContentVerifier(IPortalController portalController, IPortalGroupController portalGroupController)
Please add a parameterless constructor

2018-05-03 08:11 UTC, Mohtshum commented
Changes pushed

2018-05-03 08:25 UTC, tpluscode approved these changes

2018-05-03 09:14 UTC, merged

2018-07-25 05:25 UTC, tpluscode commented
partially fixes dnnsoftware/Dnn.AdminExperience.Extensions#571